# Generated by Django 3.2.3 on 2021-05-22 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_auto_20210521_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='School',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.school'),
        ),
    ]
